"""Added UserWeightHistory table

Revision ID: 098dd2046b74
Revises: bd577360b581
Create Date: 2024-11-12 00:53:07.542982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '098dd2046b74'
down_revision = 'bd577360b581'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('WeightHistory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_selected', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('WeightHistory', schema=None) as batch_op:
        batch_op.drop_column('date_selected')

    # ### end Alembic commands ###
